### ISSUE TITLE
[oxygen-cli][1.13.3] Maximum call stack size exceeded error encountered after some test failures

### ISSUE THREAD

**Issue by starchen** [oxygenhq/oxygen#102]
Hi,

after upgrading oxygen-cli from 1.10.0 to 1.13.3, we've encountered errors like this when several tests failed:

> [36minfo[39m: [Oxygen] Executing: log.onAfterCase({"type":"UNKNOWN_ERROR","message":"undefined: Maximum call stack size exceeded","data":"RangeError: Maximum call stack size exceeded\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:75:22)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)\n    at hookedLoader (/usr/local/lib/node_modules/oxygen-cli/node_modules/mockery/mockery.js:111:12)"

We tried to dispose by calling web.dispose on afterCase hook but the problem is still there.
Is it linked to this https://github.com/oxygenhq/oxygen/issues/20 ?

**Comment by romovs** [comment]
Should be fixed in v1.13.4.

**Comment by starchen** [comment]
Thank you for your responsiveness.
It is indeed fixed in v1.13.4.
